/**
 * APP ROUTES - Centralized route definitions
 * Use these constants throughout the app instead of hardcoded strings
 */

export const APP_ROUTES = {
  HOME: "/",
  CATEGORIES: "/categories",
  CATEGORY_DETAIL: (id) => `/categories/${id}`,
  PRODUCT: (id) => `/product/${id}`,
  NEW_ARRIVALS: "/new-arrivals",
  CART: "/cart",
  ORDER_SUMMARY: "/order-summary",
  ADDRESSES: "/addresses",
  ADDRESS_NEW: "/addresses/new",
  ADDRESS_EDIT: (id) => `/addresses/${id}/edit`,
  COUPON: "/coupon",
  PAYMENT: "/payment",
  PAYMENT_METHOD: "/payment-method",
  PAYMENT_METHOD_NEW_CARD: "/payment-method/new-card",
  SCHEME: "/scheme",
  FESTIVAL_SCHEME: "/FestivalScheme",
  SUCCESS: "/success",
  ORDERS: "/orders",
  ORDER_DETAIL: (id) => `/orders/${id}`,
  WISHLIST: "/wishlist",
  PROFILE: "/profile",
  PROFILE_EDIT: "/profile-edit",
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  HELP_SUPPORT: "/help-support",
  LOGIN: "/login",
};

export const APP_ROUTES_WITH_BACK = {
  CATEGORIES: { back: "/", label: "Back to Home" },
  CATEGORY_DETAIL: { back: "/categories", label: "Back to Categories" },
  PRODUCT: { back: "/categories", label: "Back to Categories" },
  NEW_ARRIVALS: { back: "/", label: "Back to Home" },
  CART: { back: "/", label: "Back to Home" },
  ORDER_SUMMARY: { back: "/cart", label: "Back to Cart" },
  ADDRESSES: { back: "/order-summary", label: "Back to Order Summary" },
  ADDRESS_NEW: { back: "/addresses", label: "Back to Addresses" },
  ADDRESS_EDIT: { back: "/addresses", label: "Back to Addresses" },
  COUPON: { back: "/order-summary", label: "Back to Order Summary" },
  PAYMENT: { back: "/order-summary", label: "Back to Order Summary" },
  PAYMENT_METHOD: { back: "/profile", label: "Back to Profile" },
  PAYMENT_METHOD_NEW_CARD: { back: "/payment-method", label: "Back to Payment Methods" },
  SCHEME: { back: "/payment", label: "Back to Payment" },
  SUCCESS: { back: "/scheme", label: "Back to Scheme" },
  ORDERS: { back: "/profile", label: "Back to Profile" },
  ORDER_DETAIL: { back: "/", label: "Back to Home" },
  WISHLIST: { back: "/profile", label: "Back to Profile" },
  PROFILE: { back: "/", label: "Back to Home" },
  PROFILE_EDIT: { back: "/profile", label: "Back to Profile" },
  SETTINGS: { back: "/profile", label: "Back to Profile" },
  NOTIFICATIONS: { back: "/profile", label: "Back to Profile" },
  HELP_SUPPORT: { back: "/profile", label: "Back to Profile" },
  LOGIN: { back: "/", label: "Back to Home" },
};
